# Generated by Django 4.2.1 on 2023-06-29 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.CharField(default=0, max_length=10)),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=200)),
                ('address', models.CharField(default='', max_length=300)),
                ('phone', models.CharField(default=0, max_length=10)),
                ('course', models.CharField(default='', max_length=300)),
                ('semester', models.IntegerField(default=0)),
                ('language', models.CharField(blank=True, default='', max_length=50, null=True)),
            ],
        ),
    ]
