# Generated by Django 4.2.1 on 2023-06-29 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='language',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
