# Generated by Django 4.2.1 on 2023-06-29 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_alter_student_language_alter_student_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='language',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
